name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.17.11"
      - name: Run Golint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.39
